default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: stor-test_development


test:
  <<: *default
  database: stor-test_test